settings:
  interval: 30
  logLebel: "INFO"

services:
  - name: "Google DNS ping"
    agent: ping
    target: "8.8.8.8"

  - name: "Google DNS"
    agent: dns
    target: "8.8.8.8"
    domain: "www.google.com"
  
  - name: "Google"
    agent: http
    target: "https://www.google.com"
